export const products = {
  "petlibro-filters-1": {
    name: "PETLIBRO Replacement Filters for Dockstream Fountain",
    price: 9.99,
    image: "https://m.media-amazon.com/images/I/71hQoQCdHKL._AC_SL1500_.jpg",
    badge: "🔄 Replacement Part",
    amazonUrl:
      "https://www.amazon.com/PETLIBRO-Replacement-Filters-Dockstream-Fountain/dp/B0B7J16VGK?th=1&linkCode=ll1&tag=purrhydrate-20&linkId=26122cbd497125f00d86f93d7e665848&language=en_US&ref_=as_li_ss_tl",
    description:
      "Keep your PETLIBRO Dockstream Fountain running smoothly with these high-quality replacement filters. Designed for optimal water filtration and easy installation, ensuring clean and fresh water for your pets every day.",
    features: ["4 Pack Filters", "Compatible with Dockstream", "Triple Action Filtration", "Long Lasting"],
    detailedFeatures: [
      "Carbon-activated filtration",
      "Prevents clogs and buildup",
      "Easy snap-in replacement",
      "BPA-free materials",
      "Improves water taste and quality",
    ],
    gradient: "from-gray-400 to-blue-400",
    specs: {
      capacity: "N/A",
      dimensions: "2.5 x 2.5 x 0.5 inches",
      weight: "0.2 lbs",
      material: "Plastic & Carbon",
      power: "N/A",
      warranty: "N/A",
    },
  },
  "veken-replacement": {
    name: "Veken Replacement Filters for Automatic Stainless Dispenser",
    price: 12.99,
    image: "https://m.media-amazon.com/images/I/81k3SQDP76L._AC_SL1500_.jpg",
    badge: "🔄 Replacement Part",
    amazonUrl:
      "https://www.amazon.com/Veken-Replacement-Automatic-Stainless-Dispenser/dp/B0BHNRDDDC?th=1&linkCode=ll1&tag=purrhydrate-20&linkId=7f10ce3959c43add0350994eeac1e977&language=en_US&ref_=as_li_ss_tl",
    description:
      "Essential replacement filters for Veken stainless steel pet fountains. These filters ensure continuous clean water flow, removing impurities and odors effectively.",
    features: ["6 Pack", "For Stainless Fountains", "Advanced Filtration", "Affordable Refills"],
    detailedFeatures: [
      "Multi-layer filtration system",
      "Removes hair, debris, and bacteria",
      "Compatible with Veken models",
      "Quick and simple to replace",
      "Enhances pet health",
    ],
    gradient: "from-gray-400 to-green-400",
    specs: {
      capacity: "N/A",
      dimensions: "3 x 3 x 0.6 inches",
      weight: "0.3 lbs",
      material: "Foam & Carbon",
      power: "N/A",
      warranty: "N/A",
    },
  },
  "veken-fountain": {
    name: "Veken Pet Fountain Automatic Dispenser with Replacement",
    price: 29.99,
    image: "https://m.media-amazon.com/images/I/71bpxyu6jrL._AC_SL1500_.jpg",
    badge: "💧 Entry Level Fountain",
    amazonUrl:
      "https://www.amazon.com/Veken-Fountain-Automatic-Dispenser-Replacement/dp/B08NCDBT7Q?th=1&linkCode=ll1&tag=purrhydrate-20&linkId=9bcbe7eeec91f75db62be74cdfc304a8&language=en_US&ref_=as_li_ss_tl",
    description:
      "The Veken Pet Fountain provides circulating fresh water for cats and dogs. Includes replacement filters for long-term use. Quiet pump ensures undisturbed rest.",
    features: ["2.5L Capacity", "Quiet Operation", "Included Filters", "Easy Clean"],
    detailedFeatures: [
      "Silent pump technology",
      "Stainless steel top",
      "Adjustable flow modes",
      "Dishwasher safe",
      "Prevents stagnation",
    ],
    gradient: "from-blue-400 to-indigo-400",
    specs: {
      capacity: "2.5 Liters",
      dimensions: "8 x 8 x 6 inches",
      weight: "2 lbs",
      material: "Stainless Steel & Plastic",
      power: "USB Powered",
      warranty: "1 Year",
    },
  },
  "imipaw-feeder": {
    name: "IMIPAW Automatic Feeders Dispenser Clog-Free",
    price: 49.99,
    image: "https://m.media-amazon.com/images/I/61y+WIPgvCL._AC_SL1500_.jpg",
    badge: "🍽️ Food Dispenser",
    amazonUrl:
      "https://www.amazon.com/IMIPAW-Automatic-Feeders-Dispenser-Clog-Free/dp/B0BR5VST5N?th=1&linkCode=ll1&tag=purrhydrate-20&linkId=3bc644d8794b12d77a637a60529205ba&language=en_US&ref_=as_li_ss_tl",
    description:
      "Automatic pet feeder with clog-free design for dry food. Program up to 6 meals a day, keeping your pet fed even when you're away.",
    features: ["4L Capacity", "6 Meals/Day", "Voice Recorder", "Anti-Clog"],
    detailedFeatures: [
      "Large capacity for weeks of food",
      "Customizable portion sizes",
      "Battery backup option",
      "Easy assembly",
      "Suitable for cats and small dogs",
    ],
    gradient: "from-orange-400 to-red-400",
    specs: {
      capacity: "4 Liters",
      dimensions: "10 x 10 x 12 inches",
      weight: "3.5 lbs",
      material: "BPA-Free Plastic",
      power: "AC Adapter",
      warranty: "1 Year",
    },
  },
  "petlibro-desiccant": {
    name: "PETLIBRO Desiccant Bags Upgrade for Automatic Feeder",
    price: 8.99,
    image: "https://m.media-amazon.com/images/I/81rPyczM6vL._AC_SL1500_.jpg",
    badge: "🔄 Accessory",
    amazonUrl:
      "https://www.amazon.com/PETLIBRO-Desiccant-Upgrade-Suitable-Automatic/dp/B08NVBYQHV?th=1&linkCode=ll1&tag=purrhydrate-20&linkId=dea982bbcc57f6454e3426cfc4218686&language=en_US&ref_=as_li_ss_tl",
    description:
      "Desiccant bags to keep pet food dry and fresh in automatic feeders. Prevents moisture and mold, extending food shelf life.",
    features: ["10 Pack", "Reusable", "Food Safe", "Easy to Use"],
    detailedFeatures: [
      "Absorbs excess humidity",
      "Compatible with PETLIBRO feeders",
      "Non-toxic materials",
      "Simple replacement",
    ],
    gradient: "from-yellow-400 to-amber-400",
    specs: {
      capacity: "N/A",
      dimensions: "4 x 6 inches",
      weight: "0.1 lbs",
      material: "Silica Gel",
      power: "N/A",
      warranty: "N/A",
    },
  },
  "automatic-feeder-4l": {
    name: "Automatic Feeder Dispenser with Recorder 4L Basic",
    price: 39.99,
    image: "https://m.media-amazon.com/images/I/61TBPvvykoL._AC_SL1500_.jpg",
    badge: "🍽️ Basic Feeder",
    amazonUrl:
      "https://www.amazon.com/Automatic-Feeder-Dispenser-Recorder-4L-Basic/dp/B0DF7H6SGZ?th=1&linkCode=ll1&tag=purrhydrate-20&linkId=7fa78086eef8d2377da802021be83b40&language=en_US&ref_=as_li_ss_tl",
    description:
      "Reliable automatic feeder with voice recorder to call your pet at mealtime. 4L capacity for extended use without refills.",
    features: ["4L Dry Food", "Voice Recording", "Timer Function", "Portable"],
    detailedFeatures: ["Up to 15s recording", "6 meals scheduling", "Anti-jam mechanism", "Power outage protection"],
    gradient: "from-green-400 to-emerald-400",
    specs: {
      capacity: "4 Liters",
      dimensions: "9 x 9 x 11 inches",
      weight: "3 lbs",
      material: "ABS Plastic",
      power: "Battery & Adapter",
      warranty: "1 Year",
    },
  },
  "gorilla-grip-mat": {
    name: "Gorilla Grip Dog Food Mat",
    price: 14.99,
    image: "https://m.media-amazon.com/images/I/817vjzRw1eL._AC_SL1500_.jpg",
    badge: "🛡️ Protective Mat",
    amazonUrl:
      "https://www.amazon.com/Gorilla-Grip-Dog-Food-Mat/dp/B081S7C5DN?th=1&linkCode=ll1&tag=purrhydrate-20&linkId=9e833d3c623240fbe3196900ed3faf94&language=en_US&ref_=as_li_ss_tl",
    description: "Non-slip mat to protect floors from spills around food and water bowls. Durable and easy to clean.",
    features: ["Waterproof", "Non-Slip", "Machine Washable", "Multiple Sizes"],
    detailedFeatures: ["Silicone construction", "Traps spills effectively", "Safe for pets", "Easy storage"],
    gradient: "from-slate-400 to-gray-400",
    specs: {
      capacity: "N/A",
      dimensions: "18 x 12 inches",
      weight: "1 lb",
      material: "Silicone",
      power: "N/A",
      warranty: "Limited Lifetime",
    },
  },
  "petkit-filters": {
    name: "PETKIT Replacement Filters for Eversweet Fountains",
    price: 11.99,
    image: "https://m.media-amazon.com/images/I/61szjkAEmqL._AC_SL1500_.jpg",
    badge: "🔄 Fountain Filters",
    amazonUrl:
      "https://www.amazon.com/PETKIT-Fountains-Eversweet-CYBERTAIL-Replacement/dp/B0BVQPJRLH?th=1&linkCode=ll1&tag=purrhydrate-20&linkId=0cf7548b097ee32aa686bb5aaee7cbd0&language=en_US&ref_=as_li_ss_tl",
    description:
      "Replacement filters for PETKIT Eversweet and CyberTail fountains. Maintains clean water with advanced filtration.",
    features: ["4 Pack", "For PETKIT Models", "Ion Exchange", "Long-Life"],
    detailedFeatures: ["Removes impurities", "Prevents algae", "Eco-friendly", "Simple installation"],
    gradient: "from-teal-400 to-cyan-400",
    specs: {
      capacity: "N/A",
      dimensions: "2 x 2 x 0.4 inches",
      weight: "0.15 lbs",
      material: "Cotton & Resin",
      power: "N/A",
      warranty: "N/A",
    },
  },
  "stainless-cat-fountain": {
    name: "Stainless Steel Cat Water Fountain",
    price: 34.99,
    image: "https://m.media-amazon.com/images/I/71QLaRKrdvL._AC_SL1500_.jpg",
    badge: "💧 Stainless Fountain",
    amazonUrl:
      "https://www.amazon.com/Cat-Water-Fountain-Stainless-Steel/dp/B0DDPYHHFX?th=1&linkCode=ll1&tag=purrhydrate-20&linkId=864a9952b3b49e60e6151136e061bef6&language=en_US&ref_=as_li_ss_tl",
    description:
      "Durable stainless steel fountain for cats, providing fresh circulating water. Quiet and hygienic design.",
    features: ["2L Capacity", "Stainless Steel", "Quiet Pump", "Filter Included"],
    detailedFeatures: ["Rust-resistant", "Multiple flow options", "Easy disassembly", "Healthier hydration"],
    gradient: "from-silver-400 to-gray-400",
    specs: {
      capacity: "2 Liters",
      dimensions: "7.8 x 7.8 x 5.5 inches",
      weight: "2.2 lbs",
      material: "304 Stainless Steel",
      power: "DC Adapter",
      warranty: "1 Year",
    },
  },
  "peggy11-dish": {
    name: "PEGGY11 Stainless Steel Premium Nonslip Dishwasher Safe Bowl",
    price: 19.99,
    image: "https://m.media-amazon.com/images/I/619GB6Oko1L._AC_SL1500_.jpg",
    badge: "🥣 Premium Bowl",
    amazonUrl:
      "https://www.amazon.com/PEGGY11-Stainless-Premium-Nonslip-Dishwasher/dp/B0BDZ8WBG6?th=1&linkCode=ll1&tag=purrhydrate-20&linkId=98a31415c22aa00e0f7c73c702e39816&language=en_US&ref_=as_li_ss_tl",
    description:
      "High-quality stainless steel bowl with non-slip base. Dishwasher safe for easy cleaning, perfect for food or water.",
    features: ["20oz Capacity", "Non-Slip Bottom", "Dishwasher Safe", "Rust Proof"],
    detailedFeatures: ["Elevated design option", "BPA-free", "Durable construction", "Pet safe"],
    gradient: "from-zinc-400 to-stone-400",
    specs: {
      capacity: "20 Ounces",
      dimensions: "6 x 6 x 3 inches",
      weight: "0.5 lbs",
      material: "Stainless Steel",
      power: "N/A",
      warranty: "Lifetime",
    },
  },
  "oneisall-feeder": {
    name: "oneisall Automatic Feeder Dispenser Indoor",
    price: 45.99,
    image: "https://m.media-amazon.com/images/I/61GGQluO1XL._AC_SL1300_.jpg",
    badge: "🍽️ Smart Feeder",
    amazonUrl:
      "https://www.amazon.com/oneisall-Automatic-Feeder-Dispenser-Indoor/dp/B0C5X2G933?th=1&linkCode=ll1&tag=purrhydrate-20&linkId=6a5a792a653b4195afa218ad6c00fcb1&language=en_US&ref_=as_li_ss_tl",
    description: "WiFi-enabled automatic feeder for indoor pets. App control for scheduling meals and monitoring.",
    features: ["5L Capacity", "App Control", "Voice Recorder", "Dual Power"],
    detailedFeatures: ["Remote feeding via app", "Portion control", "Anti-block design", "Suitable for multiple pets"],
    gradient: "from-purple-400 to-violet-400",
    specs: {
      capacity: "5 Liters",
      dimensions: "11 x 11 x 13 inches",
      weight: "4 lbs",
      material: "Food-Grade Plastic",
      power: "Adapter & Battery",
      warranty: "2 Years",
    },
  },
  "petlibro-fountain": {
    name: "PETLIBRO Cat Water Fountain Stainless Steel Wireless Dispenser",
    price: 54.99,
    image: "https://m.media-amazon.com/images/I/612wMQBovTL._AC_SL1500_.jpg",
    badge: "💧 Wireless Fountain",
    amazonUrl:
      "https://www.amazon.com/PETLIBRO-Fountain-Stainless-Wireless-Dispenser/dp/B0F32Z6V7L?th=1&linkCode=ll1&tag=purrhydrate-20&linkId=6d13f81dcbd9e5b89119db7f4bb0a984&language=en_US&ref_=as_li_ss_tl",
    description:
      "Wireless stainless steel fountain with large capacity and quiet operation. Ideal for cats preferring running water.",
    features: ["3.5L Capacity", "Stainless Steel", "Cordless Pump", "5 Flow Modes"],
    detailedFeatures: ["Rechargeable battery", "Triple filtration", "Anti-slip base", "Low water alert"],
    gradient: "from-indigo-400 to-purple-400",
    specs: {
      capacity: "3.5 Liters",
      dimensions: "10 x 10 x 8 inches",
      weight: "3.2 lbs",
      material: "Stainless Steel",
      power: "Rechargeable Battery",
      warranty: "1 Year",
    },
  },
  "kitty-city-bowls": {
    name: "Kitty City Raised Cat Ear Bowls Small 2pk Modern",
    price: 9.34,
    image: "https://m.media-amazon.com/images/I/71+aXTecSkL._AC_SL1500_.jpg",
    badge: "🥣 Raised Bowls",
    amazonUrl:
      "https://www.amazon.com/Kitty-City-Raised-Collection-Waterer/dp/B0CT67JCQY?&linkCode=ll1&tag=purrhydrate-20&linkId=ca5f15436c3dd03e28701f79569c8e31&language=en_US&ref_=as_li_ss_tl",
    description:
      "Stylish raised cat ear bowls in a set of 2. Promotes better posture and reduces neck strain during meals.",
    features: ["2 Pack", "Raised Design", "Ceramic Material", "Modern Look"],
    detailedFeatures: ["Whisker-friendly", "Microwave safe", "Stable base", "Easy to clean"],
    gradient: "from-rose-400 to-pink-400",
    specs: {
      capacity: "8 Ounces Each",
      dimensions: "5 x 5 x 2.5 inches",
      weight: "1 lb",
      material: "Ceramic",
      power: "N/A",
      warranty: "N/A",
    },
  },
  "petlibro-filters-2": {
    name: "PETLIBRO Replacement Filters for Dockstream Fountain (Pack of 4)",
    price: 9.99,
    image: "https://m.media-amazon.com/images/I/715BJDFWERL._AC_SL1500_.jpg",
    badge: "🔄 Bulk Filters",
    amazonUrl:
      "https://www.amazon.com/PETLIBRO-Replacement-Filters-Dockstream-Fountain/dp/B0B7HXNJRP?th=1&linkCode=ll1&tag=purrhydrate-20&linkId=8d4248c2477002b8bd2085a704844adf&language=en_US&ref_=as_li_ss_tl",
    description: "Bulk pack of replacement filters for PETLIBRO fountains. Ensures ongoing purity in pet water supply.",
    features: ["4 Filters", "High Flow", "Odor Control", "Compatible"],
    detailedFeatures: ["Activated carbon layer", "Ion exchange resin", "Cotton pre-filter", "Lasts 2-4 weeks"],
    gradient: "from-blue-400 to-navy-400",
    specs: {
      capacity: "N/A",
      dimensions: "2.4 x 2.4 x 0.5 inches",
      weight: "0.2 lbs",
      material: "Multi-Layer",
      power: "N/A",
      warranty: "N/A",
    },
  },
  "catit-flower": {
    name: "Catit Flower Fountain with Triple Action Filter",
    price: 24.99,
    image: "https://m.media-amazon.com/images/I/61BhM8Zl27L._AC_SL1500_.jpg",
    badge: "🌸 Fun Design",
    amazonUrl:
      "https://www.amazon.com/Catit-Flower-Fountain-Triple-Action-Filter/dp/B0146QXOB0?th=1&linkCode=ll1&tag=purrhydrate-20&linkId=48f1406c99a5741b58bdc46711654129&language=en_US&ref_=as_li_ss_tl",
    description:
      "Whimsical flower-shaped fountain encourages cats to drink more. Triple action filter keeps water fresh and clean.",
    features: ["3L Capacity", "Flower Design", "Triple Filter", "Quiet Pump"],
    detailedFeatures: ["Encourages drinking", "Adjustable flower positions", "BPA-free", "Easy to assemble"],
    gradient: "from-pink-400 to-rose-400",
    specs: {
      capacity: "3 Liters",
      dimensions: "9.5 x 8 x 7.5 inches",
      weight: "2.6 lbs",
      material: "Plastic",
      power: "AC Adapter",
      warranty: "1 Year",
    },
  },
  "petlibro-monitoring": {
    name: "PETLIBRO Monitoring Dockstream Automatic Dispenser",
    price: 69.99,
    image: "https://m.media-amazon.com/images/I/6102YDWDjOL._AC_SL1500_.jpg",
    badge: "📱 App Monitored",
    amazonUrl:
      "https://www.amazon.com/PETLIBRO-Monitoring-Dockstream-Automatic-Dispenser/dp/B0CBN7SM2R?th=1&linkCode=ll1&tag=purrhydrate-20&linkId=c979b0631fffb4ff15ca981b8a3c656c&language=en_US&ref_=as_li_ss_tl",
    description:
      "Smart water fountain with app monitoring for water levels and intake. Tracks your pet's hydration habits.",
    features: ["2.5L Capacity", "App Integration", "Auto-Refill", "Health Tracking"],
    detailedFeatures: ["Real-time notifications", "Camera option", "Quiet wireless pump", "Multi-pet support"],
    gradient: "from-violet-400 to-fuchsia-400",
    specs: {
      capacity: "2.5 Liters",
      dimensions: "8.5 x 8.5 x 6.5 inches",
      weight: "2.8 lbs",
      material: "Plastic & Stainless",
      power: "USB",
      warranty: "2 Years",
    },
  },
  "petsafe-drinkwell": {
    name: "PetSafe Drinkwell Multi-Pet Stainless Fountain",
    price: 59.99,
    image: "https://m.media-amazon.com/images/I/71lzKycY7XL._AC_SX679_.jpg",
    badge: "🐕 Multi-Pet",
    amazonUrl:
      "https://www.amazon.com/PetSafe-Drinkwell-Multi-Pet-Stainless-Fountain/dp/B002SB91QS?th=1&linkCode=ll1&tag=purrhydrate-20&linkId=1634f3cb1934dbce34abcc06ecc5313f&language=en_US&ref_=as_li_ss_tl",
    description: "Large capacity fountain for multiple pets. Stainless steel for durability and easy cleaning.",
    features: ["168oz Capacity", "Stainless Steel", "Free-Falling Stream", "Adjustable Ramp"],
    detailedFeatures: ["Charcoal filter", "Dishwasher safe", "Quiet operation", "For up to 5 pets"],
    gradient: "from-green-400 to-lime-400",
    specs: {
      capacity: "168 Ounces",
      dimensions: "14 x 14 x 10 inches",
      weight: "5 lbs",
      material: "Stainless Steel",
      power: "AC Adapter",
      warranty: "1 Year",
    },
  },
  "veken-pump-filters": {
    name: "Veken Water Fountain Pump with Filters",
    price: 15.99,
    image: "https://m.media-amazon.com/images/I/71nvO76fr7L._AC_SX679_.jpg",
    badge: "🔧 Pump Replacement",
    amazonUrl:
      "https://www.amazon.com/Water-Fountain-Pump-Veken-Filters/dp/B0FMF59BR2?th=1&linkCode=ll1&tag=purrhydrate-20&linkId=95cac7acd36ba948311ab80058580f9c&language=en_US&ref_=as_li_ss_tl",
    description: "Replacement pump and filters for Veken fountains. Ensures continued reliable performance.",
    features: ["Quiet Pump", "4 Filters", "Universal Fit", "Low Noise"],
    detailedFeatures: ["5W power efficient", "Easy swap", "Compatible with 2L models", "Durable motor"],
    gradient: "from-red-400 to-orange-400",
    specs: {
      capacity: "N/A",
      dimensions: "2 x 2 x 1.5 inches",
      weight: "0.4 lbs",
      material: "Plastic",
      power: "5W",
      warranty: "6 Months",
    },
  },
  "veken-innovation": {
    name: "Veken Innovation Stainless Automatic Fountain Replacement",
    price: 32.99,
    image: "https://m.media-amazon.com/images/I/716Ddez-29L._AC_SX466_.jpg",
    badge: "⭐ Upgraded Fountain",
    popular: true,
    amazonUrl:
      "https://www.amazon.com/Veken-Innovation-Stainless-Automatic-Replacement/dp/B0CK1MXC7J?th=1&linkCode=ll1&tag=purrhydrate-20&linkId=e1bcb409a226c4e7bdcbe047d47c819d&language=en_US&ref_=as_li_ss_tl",
    description: "Innovative stainless steel fountain with automatic cleaning features. Keeps water pristine longer.",
    features: ["3L Capacity", "Self-Cleaning", "Stainless Build", "Quiet"],
    detailedFeatures: ["UV light option", "360-degree flow", "App compatible", "Filter reminders"],
    gradient: "from-cyan-400 to-sky-400",
    specs: {
      capacity: "3 Liters",
      dimensions: "9 x 9 x 7 inches",
      weight: "2.7 lbs",
      material: "Stainless Steel",
      power: "USB-C",
      warranty: "18 Months",
    },
  },
  "misfans-fountain": {
    name: "MISFANS Designed Automatic Fountain Dispenser Replaceable",
    price: 44.99,
    image: "https://m.media-amazon.com/images/I/71DY1ncHfmL._AC_SX466_PIbundle-4,TopRight,0,0_SH20_.jpg",
    badge: "💧 Modern Dispenser",
    amazonUrl:
      "https://www.amazon.com/Fountain-MISFANS-Designed-Automatic-Dispenser-Replaceable/dp/B0F5N61BBN?th=1&linkCode=ll1&tag=purrhydrate-20&linkId=3161fc05acee3dd011187d0483a72660&language=en_US&ref_=as_li_ss_tl",
    description:
      "Stylish automatic water dispenser with replaceable parts for longevity. Encourages pets to stay hydrated.",
    features: ["4L Capacity", "Replaceable Parts", "LED Lights", "Multiple Modes"],
    detailedFeatures: ["Smart sensor", "Anti-overflow", "Wireless charging", "Elegant design"],
    gradient: "from-emerald-400 to-teal-400",
    specs: {
      capacity: "4 Liters",
      dimensions: "11 x 11 x 9 inches",
      weight: "3.8 lbs",
      material: "ABS & Glass",
      power: "Wireless",
      warranty: "1 Year",
    },
  },
  "wopet-fountain": {
    name: "WOPET Fountain Dispenser Automatic with Filters",
    price: 38.99,
    image: "https://m.media-amazon.com/images/I/71aeUwf4xWL._AC_SX679_.jpg",
    badge: "💧 Automatic Flow",
    amazonUrl:
      "https://www.amazon.com/WOPET-Fountain-Dispenser-Automatic-Filters/dp/B0FQNVP965?th=1&linkCode=ll1&tag=purrhydrate-20&linkId=8870156fd5db20539266f3a49432a575&language=en_US&ref_=as_li_ss_tl",
    description: "Automatic pet fountain with included filters for hassle-free hydration. Compact and efficient.",
    features: ["2.8L Capacity", "Auto On/Off", "Filter Kit", "Quiet Motor"],
    detailedFeatures: ["Water level sensor", "Easy fill top", "Pet-safe materials", "Travel friendly"],
    gradient: "from-lime-400 to-green-400",
    specs: {
      capacity: "2.8 Liters",
      dimensions: "8.3 x 8.3 x 6.7 inches",
      weight: "2.1 lbs",
      material: "Plastic",
      power: "USB",
      warranty: "1 Year",
    },
  },
  "feelneedy-separator": {
    name: "FEELNEEDY Wastewater Separation Stainless Dispenser",
    price: 52.99,
    image: "https://m.media-amazon.com/images/I/61h6AIoARIL._AC_SX679_.jpg",
    badge: "🧼 Hygienic Design",
    amazonUrl:
      "https://www.amazon.com/Wastewater-Separation-FEELNEEDY-Stainless-Dispenser/dp/B0F9FC7JYD?&linkCode=ll1&tag=purrhydrate-20&linkId=22dc4a7b467b3d5a4ef1c1546087fe21&language=en_US&ref_=as_li_ss_tl",
    description:
      "Innovative fountain with wastewater separation for ultra-clean drinking water. Stainless steel for hygiene.",
    features: ["3.2L Capacity", "Waste Separation", "Stainless Steel", "Self-Clean"],
    detailedFeatures: ["Dual chamber system", "Reduces bacteria", "Touch control", "Long battery life"],
    gradient: "from-fuchsia-400 to-pink-400",
    specs: {
      capacity: "3.2 Liters",
      dimensions: "9.5 x 9.5 x 7.5 inches",
      weight: "3 lbs",
      material: "Stainless Steel",
      power: "Battery",
      warranty: "2 Years",
    },
  },
  "lalahome-dispenser": {
    name: "LALAHOME Automatic Dispenser with Wastewater Separation",
    price: 47.99,
    image: "https://m.media-amazon.com/images/I/61+uFI49L5L._AC_SX679_.jpg",
    badge: "🧼 Clean Tech",
    amazonUrl:
      "https://www.amazon.com/LALAHOME-Automatic-Dispenser-Wastewater-Separation/dp/B0FBWZL93D?th=1&linkCode=ll1&tag=purrhydrate-20&linkId=42689d020ab37b24348fccebacf4e607&language=en_US&ref_=as_li_ss_tl",
    description: "Advanced automatic water dispenser featuring wastewater separation technology for fresher water.",
    features: ["4L Capacity", "Separation Tech", "Quiet Pump", "App Alert"],
    detailedFeatures: ["Smart filtration", "Auto clean cycle", "UV sanitization", "Multi-flow settings"],
    gradient: "from-amber-400 to-orange-400",
    specs: {
      capacity: "4 Liters",
      dimensions: "10.5 x 10.5 x 8 inches",
      weight: "3.5 lbs",
      material: "Stainless & Plastic",
      power: "Rechargeable",
      warranty: "1 Year",
    },
  },
}
